module.exports = {
  SIGNIN: '/auth/signin',
  SIGNUP: '/auth/signup',
  SIGNOUT: '/auth/signout',
  PROFILE: '/auth/profile',
  PASSWORD: '/auth/password',
  UPDATE: '/auth/update',
  CONTROL_PANEL: '/',
  EDIT_PROFILE: '/auth/edit_profile',
  ADMIN_SIGNIN: '/auth/admin/signin',
  ADMIN_MNG: '/administrator',
  USER: '/administrator/user',
  ROLE: '/administrator/role',
  USER_ROLE: '/administrator/userrole',
  ROLE_RELATION: '/administrator/rolerelation',
};
